version: '3'

services:
  server:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
  database:
    build: db/
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: